// Package actuator Code generated by swaggo/swag. DO NOT EDIT
package actuator

import "github.com/swaggo/swag"

const docTemplateactuator = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/karabasBaRaBaS-1276/user-service",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/karabasBaRaBaS-1276/user-service"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health/liveness": {
            "get": {
                "description": "Простая проверка работоспособности, чтобы узнать, запущено ли приложение",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actuator"
                ],
                "summary": "Проверка приложения на запуск",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/actuator.LivenessResponse"
                        }
                    }
                }
            }
        },
        "/health/readiness": {
            "get": {
                "description": "Простая проверка работоспособности, чтобы узнать, готово ли приложение принимать запросы на обработку",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actuator"
                ],
                "summary": "Проверка приложения к приему трафика",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/actuator.ReadinessResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/actuator.ReadinessResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "actuator.LivenessResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "UP"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-02-09T15:04:05Z"
                }
            }
        },
        "actuator.ReadinessCheck": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "connected"
                },
                "status": {
                    "type": "string",
                    "example": "UP"
                }
            }
        },
        "actuator.ReadinessResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/actuator.ReadinessCheck"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "UP"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Эндпоинты для мониторинга состояния приложения, сбора метрик и доступа к информации о среде",
            "name": "Actuator"
        }
    ]
}`

// SwaggerInfoactuator holds exported Swagger Info so clients can modify it
var SwaggerInfoactuator = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/actuator",
	Schemes:          []string{},
	Title:            "API с Actuator-эндпоинтами",
	Description:      "Инфраструктурный слой (Actuator) — Code-First с Actuator-эндпоинтами.",
	InfoInstanceName: "actuator",
	SwaggerTemplate:  docTemplateactuator,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoactuator.InstanceName(), SwaggerInfoactuator)
}
