//go:build go1.22

// Package userapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package userapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Шаг 1. Инициализация авторизации через OAuth 2.0
	// (GET /oauth/authorize)
	InitiateOAuthAuthorization(w http.ResponseWriter, r *http.Request, params InitiateOAuthAuthorizationParams)
	// Получение открытых ключей JSON Web Key Set (JWKS)
	// (GET /oauth/jwks)
	GetOauthJwks(w http.ResponseWriter, r *http.Request)
	// Шаг 2. Аутентификация пользователя
	// (POST /oauth/login)
	LoginUser(w http.ResponseWriter, r *http.Request, params LoginUserParams)
	// Шаг 3. Обмен кода на токен
	// (POST /oauth/token)
	ExchangeAuthorizationCode(w http.ResponseWriter, r *http.Request)
	// Создать нового пользователя (как альтернатива шага 2 аутентификации пользователя через /oauth/login)
	// (POST /user)
	CreateUserFull(w http.ResponseWriter, r *http.Request, params CreateUserFullParams)
	// Удаление пользователя
	// (DELETE /user/{username})
	DeleteUserByUsername(w http.ResponseWriter, r *http.Request, username Username, params DeleteUserByUsernameParams)
	// Поиск пользователя по его username
	// (GET /user/{username})
	GetUserByUsername(w http.ResponseWriter, r *http.Request, username Username, params GetUserByUsernameParams)
	// Обновить информацию о пользователе
	// (PATCH /user/{username})
	UpdateUserByUsername(w http.ResponseWriter, r *http.Request, username Username, params UpdateUserByUsernameParams)
	// Восстановление ранее удаленного пользователя
	// (POST /user/{username}/restore)
	RestoreUserByUsername(w http.ResponseWriter, r *http.Request, username Username, params RestoreUserByUsernameParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// InitiateOAuthAuthorization operation middleware
func (siw *ServerInterfaceWrapper) InitiateOAuthAuthorization(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params InitiateOAuthAuthorizationParams

	// ------------- Required query parameter "response_type" -------------

	if paramValue := r.URL.Query().Get("response_type"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "response_type"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "response_type", r.URL.Query(), &params.ResponseType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "response_type", Err: err})
		return
	}

	// ------------- Required query parameter "client_id" -------------

	if paramValue := r.URL.Query().Get("client_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "client_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "client_id", r.URL.Query(), &params.ClientId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_id", Err: err})
		return
	}

	// ------------- Required query parameter "redirect_uri" -------------

	if paramValue := r.URL.Query().Get("redirect_uri"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "redirect_uri"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "redirect_uri", r.URL.Query(), &params.RedirectUri)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_uri", Err: err})
		return
	}

	// ------------- Required query parameter "scope" -------------

	if paramValue := r.URL.Query().Get("scope"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "scope"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "code_challenge_method" -------------

	err = runtime.BindQueryParameter("form", true, false, "code_challenge_method", r.URL.Query(), &params.CodeChallengeMethod)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code_challenge_method", Err: err})
		return
	}

	// ------------- Optional query parameter "code_challenge" -------------

	err = runtime.BindQueryParameter("form", true, false, "code_challenge", r.URL.Query(), &params.CodeChallenge)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code_challenge", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InitiateOAuthAuthorization(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOauthJwks operation middleware
func (siw *ServerInterfaceWrapper) GetOauthJwks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOauthJwks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params LoginUserParams

	// ------------- Required query parameter "code" -------------

	if paramValue := r.URL.Query().Get("code"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExchangeAuthorizationCode operation middleware
func (siw *ServerInterfaceWrapper) ExchangeAuthorizationCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExchangeAuthorizationCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUserFull operation middleware
func (siw *ServerInterfaceWrapper) CreateUserFull(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateUserFullParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, false, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = XRequestID

	} else {
		err := fmt.Errorf("Header parameter X-Request-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Request-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUserFull(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUserByUsername operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserByUsername(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username Username

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteUserByUsernameParams

	headers := r.Header

	// ------------- Required header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = XRequestID

	} else {
		err := fmt.Errorf("Header parameter X-Request-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Request-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUserByUsername(w, r, username, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserByUsername operation middleware
func (siw *ServerInterfaceWrapper) GetUserByUsername(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username Username

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserByUsernameParams

	headers := r.Header

	// ------------- Required header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = XRequestID

	} else {
		err := fmt.Errorf("Header parameter X-Request-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Request-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserByUsername(w, r, username, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUserByUsername operation middleware
func (siw *ServerInterfaceWrapper) UpdateUserByUsername(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username Username

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateUserByUsernameParams

	headers := r.Header

	// ------------- Required header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = XRequestID

	} else {
		err := fmt.Errorf("Header parameter X-Request-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Request-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUserByUsername(w, r, username, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreUserByUsername operation middleware
func (siw *ServerInterfaceWrapper) RestoreUserByUsername(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username Username

	err = runtime.BindStyledParameterWithOptions("simple", "username", r.PathValue("username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RestoreUserByUsernameParams

	headers := r.Header

	// ------------- Required header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = XRequestID

	} else {
		err := fmt.Errorf("Header parameter X-Request-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Request-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreUserByUsername(w, r, username, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/oauth/authorize", wrapper.InitiateOAuthAuthorization)
	m.HandleFunc("GET "+options.BaseURL+"/oauth/jwks", wrapper.GetOauthJwks)
	m.HandleFunc("POST "+options.BaseURL+"/oauth/login", wrapper.LoginUser)
	m.HandleFunc("POST "+options.BaseURL+"/oauth/token", wrapper.ExchangeAuthorizationCode)
	m.HandleFunc("POST "+options.BaseURL+"/user", wrapper.CreateUserFull)
	m.HandleFunc("DELETE "+options.BaseURL+"/user/{username}", wrapper.DeleteUserByUsername)
	m.HandleFunc("GET "+options.BaseURL+"/user/{username}", wrapper.GetUserByUsername)
	m.HandleFunc("PATCH "+options.BaseURL+"/user/{username}", wrapper.UpdateUserByUsername)
	m.HandleFunc("POST "+options.BaseURL+"/user/{username}/restore", wrapper.RestoreUserByUsername)

	return m
}

type InitiateOAuthAuthorizationRequestObject struct {
	Params InitiateOAuthAuthorizationParams
}

type InitiateOAuthAuthorizationResponseObject interface {
	VisitInitiateOAuthAuthorizationResponse(w http.ResponseWriter) error
}

type InitiateOAuthAuthorization302ResponseHeaders struct {
	CacheControl string
	Location     string
	Pragma       string
}

type InitiateOAuthAuthorization302Response struct {
	Headers InitiateOAuthAuthorization302ResponseHeaders
}

func (response InitiateOAuthAuthorization302Response) VisitInitiateOAuthAuthorizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Pragma", fmt.Sprint(response.Headers.Pragma))
	w.WriteHeader(302)
	return nil
}

type InitiateOAuthAuthorizationdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response InitiateOAuthAuthorizationdefaultJSONResponse) VisitInitiateOAuthAuthorizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetOauthJwksRequestObject struct {
}

type GetOauthJwksResponseObject interface {
	VisitGetOauthJwksResponse(w http.ResponseWriter) error
}

type GetOauthJwks200JSONResponse struct {
	Keys *[]Jwk `json:"keys,omitempty"`
}

func (response GetOauthJwks200JSONResponse) VisitGetOauthJwksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOauthJwksdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetOauthJwksdefaultJSONResponse) VisitGetOauthJwksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type LoginUserRequestObject struct {
	Params LoginUserParams
	Body   *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser302ResponseHeaders struct {
	CacheControl string
	Location     string
	Pragma       string
}

type LoginUser302Response struct {
	Headers LoginUser302ResponseHeaders
}

func (response LoginUser302Response) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Pragma", fmt.Sprint(response.Headers.Pragma))
	w.WriteHeader(302)
	return nil
}

type LoginUserdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response LoginUserdefaultJSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ExchangeAuthorizationCodeRequestObject struct {
	Body *ExchangeAuthorizationCodeFormdataRequestBody
}

type ExchangeAuthorizationCodeResponseObject interface {
	VisitExchangeAuthorizationCodeResponse(w http.ResponseWriter) error
}

type ExchangeAuthorizationCode200ResponseHeaders struct {
	CacheControl string
	Pragma       string
}

type ExchangeAuthorizationCode200JSONResponse struct {
	Body    AccessTokenResponse
	Headers ExchangeAuthorizationCode200ResponseHeaders
}

func (response ExchangeAuthorizationCode200JSONResponse) VisitExchangeAuthorizationCodeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))
	w.Header().Set("Pragma", fmt.Sprint(response.Headers.Pragma))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ExchangeAuthorizationCodedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ExchangeAuthorizationCodedefaultJSONResponse) VisitExchangeAuthorizationCodeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateUserFullRequestObject struct {
	Params CreateUserFullParams
	Body   *CreateUserFullJSONRequestBody
}

type CreateUserFullResponseObject interface {
	VisitCreateUserFullResponse(w http.ResponseWriter) error
}

type CreateUserFull201JSONResponse UserIdInfo

func (response CreateUserFull201JSONResponse) VisitCreateUserFullResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserFull302ResponseHeaders struct {
	CacheControl string
	Location     string
	Pragma       string
}

type CreateUserFull302Response struct {
	Headers CreateUserFull302ResponseHeaders
}

func (response CreateUserFull302Response) VisitCreateUserFullResponse(w http.ResponseWriter) error {
	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.Header().Set("Pragma", fmt.Sprint(response.Headers.Pragma))
	w.WriteHeader(302)
	return nil
}

type CreateUserFulldefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CreateUserFulldefaultJSONResponse) VisitCreateUserFullResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteUserByUsernameRequestObject struct {
	Username Username `json:"username"`
	Params   DeleteUserByUsernameParams
}

type DeleteUserByUsernameResponseObject interface {
	VisitDeleteUserByUsernameResponse(w http.ResponseWriter) error
}

type DeleteUserByUsername204Response struct {
}

func (response DeleteUserByUsername204Response) VisitDeleteUserByUsernameResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteUserByUsername304Response struct {
}

func (response DeleteUserByUsername304Response) VisitDeleteUserByUsernameResponse(w http.ResponseWriter) error {
	w.WriteHeader(304)
	return nil
}

type DeleteUserByUsername404Response struct {
}

func (response DeleteUserByUsername404Response) VisitDeleteUserByUsernameResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type DeleteUserByUsernamedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response DeleteUserByUsernamedefaultJSONResponse) VisitDeleteUserByUsernameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetUserByUsernameRequestObject struct {
	Username Username `json:"username"`
	Params   GetUserByUsernameParams
}

type GetUserByUsernameResponseObject interface {
	VisitGetUserByUsernameResponse(w http.ResponseWriter) error
}

type GetUserByUsername200JSONResponse User

func (response GetUserByUsername200JSONResponse) VisitGetUserByUsernameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserByUsername404Response struct {
}

func (response GetUserByUsername404Response) VisitGetUserByUsernameResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetUserByUsernamedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetUserByUsernamedefaultJSONResponse) VisitGetUserByUsernameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type UpdateUserByUsernameRequestObject struct {
	Username Username `json:"username"`
	Params   UpdateUserByUsernameParams
	Body     *UpdateUserByUsernameJSONRequestBody
}

type UpdateUserByUsernameResponseObject interface {
	VisitUpdateUserByUsernameResponse(w http.ResponseWriter) error
}

type UpdateUserByUsername204Response struct {
}

func (response UpdateUserByUsername204Response) VisitUpdateUserByUsernameResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateUserByUsername304Response struct {
}

func (response UpdateUserByUsername304Response) VisitUpdateUserByUsernameResponse(w http.ResponseWriter) error {
	w.WriteHeader(304)
	return nil
}

type UpdateUserByUsername404Response struct {
}

func (response UpdateUserByUsername404Response) VisitUpdateUserByUsernameResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateUserByUsernamedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response UpdateUserByUsernamedefaultJSONResponse) VisitUpdateUserByUsernameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RestoreUserByUsernameRequestObject struct {
	Username Username `json:"username"`
	Params   RestoreUserByUsernameParams
}

type RestoreUserByUsernameResponseObject interface {
	VisitRestoreUserByUsernameResponse(w http.ResponseWriter) error
}

type RestoreUserByUsername204Response struct {
}

func (response RestoreUserByUsername204Response) VisitRestoreUserByUsernameResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RestoreUserByUsername404Response struct {
}

func (response RestoreUserByUsername404Response) VisitRestoreUserByUsernameResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type RestoreUserByUsernamedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response RestoreUserByUsernamedefaultJSONResponse) VisitRestoreUserByUsernameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Шаг 1. Инициализация авторизации через OAuth 2.0
	// (GET /oauth/authorize)
	InitiateOAuthAuthorization(ctx context.Context, request InitiateOAuthAuthorizationRequestObject) (InitiateOAuthAuthorizationResponseObject, error)
	// Получение открытых ключей JSON Web Key Set (JWKS)
	// (GET /oauth/jwks)
	GetOauthJwks(ctx context.Context, request GetOauthJwksRequestObject) (GetOauthJwksResponseObject, error)
	// Шаг 2. Аутентификация пользователя
	// (POST /oauth/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// Шаг 3. Обмен кода на токен
	// (POST /oauth/token)
	ExchangeAuthorizationCode(ctx context.Context, request ExchangeAuthorizationCodeRequestObject) (ExchangeAuthorizationCodeResponseObject, error)
	// Создать нового пользователя (как альтернатива шага 2 аутентификации пользователя через /oauth/login)
	// (POST /user)
	CreateUserFull(ctx context.Context, request CreateUserFullRequestObject) (CreateUserFullResponseObject, error)
	// Удаление пользователя
	// (DELETE /user/{username})
	DeleteUserByUsername(ctx context.Context, request DeleteUserByUsernameRequestObject) (DeleteUserByUsernameResponseObject, error)
	// Поиск пользователя по его username
	// (GET /user/{username})
	GetUserByUsername(ctx context.Context, request GetUserByUsernameRequestObject) (GetUserByUsernameResponseObject, error)
	// Обновить информацию о пользователе
	// (PATCH /user/{username})
	UpdateUserByUsername(ctx context.Context, request UpdateUserByUsernameRequestObject) (UpdateUserByUsernameResponseObject, error)
	// Восстановление ранее удаленного пользователя
	// (POST /user/{username}/restore)
	RestoreUserByUsername(ctx context.Context, request RestoreUserByUsernameRequestObject) (RestoreUserByUsernameResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// InitiateOAuthAuthorization operation middleware
func (sh *strictHandler) InitiateOAuthAuthorization(w http.ResponseWriter, r *http.Request, params InitiateOAuthAuthorizationParams) {
	var request InitiateOAuthAuthorizationRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InitiateOAuthAuthorization(ctx, request.(InitiateOAuthAuthorizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InitiateOAuthAuthorization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InitiateOAuthAuthorizationResponseObject); ok {
		if err := validResponse.VisitInitiateOAuthAuthorizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOauthJwks operation middleware
func (sh *strictHandler) GetOauthJwks(w http.ResponseWriter, r *http.Request) {
	var request GetOauthJwksRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOauthJwks(ctx, request.(GetOauthJwksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOauthJwks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOauthJwksResponseObject); ok {
		if err := validResponse.VisitGetOauthJwksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(w http.ResponseWriter, r *http.Request, params LoginUserParams) {
	var request LoginUserRequestObject

	request.Params = params

	var body LoginUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx, request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		if err := validResponse.VisitLoginUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExchangeAuthorizationCode operation middleware
func (sh *strictHandler) ExchangeAuthorizationCode(w http.ResponseWriter, r *http.Request) {
	var request ExchangeAuthorizationCodeRequestObject

	if err := r.ParseForm(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode formdata: %w", err))
		return
	}
	var body ExchangeAuthorizationCodeFormdataRequestBody
	if err := runtime.BindForm(&body, r.Form, nil, nil); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't bind formdata: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExchangeAuthorizationCode(ctx, request.(ExchangeAuthorizationCodeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExchangeAuthorizationCode")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExchangeAuthorizationCodeResponseObject); ok {
		if err := validResponse.VisitExchangeAuthorizationCodeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUserFull operation middleware
func (sh *strictHandler) CreateUserFull(w http.ResponseWriter, r *http.Request, params CreateUserFullParams) {
	var request CreateUserFullRequestObject

	request.Params = params

	var body CreateUserFullJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUserFull(ctx, request.(CreateUserFullRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUserFull")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateUserFullResponseObject); ok {
		if err := validResponse.VisitCreateUserFullResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteUserByUsername operation middleware
func (sh *strictHandler) DeleteUserByUsername(w http.ResponseWriter, r *http.Request, username Username, params DeleteUserByUsernameParams) {
	var request DeleteUserByUsernameRequestObject

	request.Username = username
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteUserByUsername(ctx, request.(DeleteUserByUsernameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteUserByUsername")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteUserByUsernameResponseObject); ok {
		if err := validResponse.VisitDeleteUserByUsernameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserByUsername operation middleware
func (sh *strictHandler) GetUserByUsername(w http.ResponseWriter, r *http.Request, username Username, params GetUserByUsernameParams) {
	var request GetUserByUsernameRequestObject

	request.Username = username
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserByUsername(ctx, request.(GetUserByUsernameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserByUsername")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserByUsernameResponseObject); ok {
		if err := validResponse.VisitGetUserByUsernameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateUserByUsername operation middleware
func (sh *strictHandler) UpdateUserByUsername(w http.ResponseWriter, r *http.Request, username Username, params UpdateUserByUsernameParams) {
	var request UpdateUserByUsernameRequestObject

	request.Username = username
	request.Params = params

	var body UpdateUserByUsernameJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUserByUsername(ctx, request.(UpdateUserByUsernameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUserByUsername")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateUserByUsernameResponseObject); ok {
		if err := validResponse.VisitUpdateUserByUsernameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RestoreUserByUsername operation middleware
func (sh *strictHandler) RestoreUserByUsername(w http.ResponseWriter, r *http.Request, username Username, params RestoreUserByUsernameParams) {
	var request RestoreUserByUsernameRequestObject

	request.Username = username
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RestoreUserByUsername(ctx, request.(RestoreUserByUsernameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RestoreUserByUsername")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RestoreUserByUsernameResponseObject); ok {
		if err := validResponse.VisitRestoreUserByUsernameResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcbXPbVnb+Kyg2nbE3BElRsmXpSy3LsiPHG6eyVCd1VA0IXJKwSIALgHpJRh1JTGK7",
	"8lrZzHY202mczW5n2i+dUrIZU5RI/YV7/1HnnAuAAHFBUrYTbzb64qFAEPfc8/Kc55xz4c9kzapULZOY",
	"riNPfyZXVVutEJfY+FfNIbapVgh81omj2UbVNSxTnpbpN/SE7Uv0lHbpMXtCX9IuPaQNtkub9Jjtp/Ab",
	"ibZpl+3SLtumXXrC6hLt0Cbt0gP2Be3SF7RFT+CuQ9pk27TD6myXPZFoi3bY5/ijE9pgX9IWeyqnZAOW",
	"rapuSU7JXKaeeCnZJr+tGTbR5WnXrpGU7GglUlFBbrKhVqpluH1+TTWtNfiXfzI0eFZF3bhNzKJbkqcv",
	"ZVNyxTD9PydSsJ5LbFj5X+6ryqczyj9nlamVq2ll+d135JTsblbhwY5rG2ZR3tpKyRsKSEIcVzF0gdb+",
	"Qju0Rdu0gUrrsD16BPt9QZu0w3Zpi33Ov+ZKk+hL2qCnoD22QxtyKrSZ/NhYIa8TXZkoTE4qEyQ3peRz",
	"+awypk/qeaIVJjSS97VWIqpO7J7ePlIWPCHnrw/UXcGyK6oLmq4ZumC/W/7N6C0zmkYcZ9FaJab3fIEG",
	"/tjbEXhDQ4Kt0jYoQKIv4DLbZXV6itut2laV2K5B8Pla2SCmu/JGFAsitOgx7dIf4BbaYvsR9VY2r6nm",
	"anzLKVmzdFE8/Ac4tEQb9NBz+BYYD7yXtlKhQOCSCcOgSw/oCQq8zwMhqp50REC15pYs2/hUBQFWUKgE",
	"YVfWiG0UDGILpH6Ggj6HkIuqDk3kBWaXPfQvt3GXFz58f3buYlQevVAq6Jcn9aJeLN64ef2SSJqirZru",
	"Cr+coEA0/7YHJM9jyquzpxIABf2BdkBlLbYThyBQHdo3pFLa9ISnjQQjCdVt1iry9H2RspfPbgyb6IZN",
	"NHelZhtxBSwtzMf8BDSBvtKUWB29+yXbg03SY7YD8HsYhYimlLFAlowvEJHYjsS+RFB+AroL27UdbHoH",
	"/+ZXmwn6iVi75LrV6UymsqnkVXM1bde8dTW1XM6r2qoQG3s4cz/sCl5I9eknFQr3fj9eDp5u5R8QzQXl",
	"RsDHqVqmQ4T+vovb3EW9BLaG7DQMfVRcYMWFFQRP/nMCisVjPwY9oPIT/ifbHeDTLyCz9j1eom3wkibb",
	"YXW2DVkCdpKQlaMRSzZvlfI3NeOOcWt+6dP5sQ+MeWfeXLikzc5fnl+tfvRPs7em0um0yJPJRtWwibNi",
	"iDTxPbpYW0LwPQJR6SHga1jfDXBdcDvaZnXagbBkX0TEG7+czQYrG6ZLisSGpVH/SRjyZ9qip5F1olu+",
	"RlQbE+Fg54yYOrJkZOsiN5yzbcueVWti76OnaN2Gb3V0BfYQGc+eRLvsEW3RAwjMmPsReLAINj20BHBr",
	"ctrFEwh6dVNiD8H2POZB2SkAxYgYEQ3Rb2kz4GMIQT0mthtlS7mQgXquUTBIWRdGHt8bJhOUjHtp3/oz",
	"YSQdvt5WkgnCGNDHIsA4+MlwSQU/vGOTgjwt/yrT48IZj9dkQgbtLabatroJf+vEVY2yI9jvd5BsMBIO",
	"+H5fyTY+YB+AougJ24sa6w89KAAgCOWCR+j+HY92hxECWLh/X5M9hvtiehYZ9sdzwMGbvGHZeUPXiTmK",
	"9zmu6tZE5vhvXJCL0e0xmSDkfLd8jkTMzxJRzj2RHU/1KLFhuuM5WQhRRoU4rlqpCuT4GrTOS6dotPc2",
	"nMvmxpWxnJK9tDiWnc5dnp6YSk9OTr2bzU5ns0Oxq7d4oA3fdiK8um0VhSDeD1WsDnb0jHrkeRDe0UpM",
	"NzEMq6qOs27ZujBcGugDx+xJRBmGUb5ivrcAuwk0HzxmUPF2JaF4+/tfX/yHq7965+/+dSWhiEu9etUb",
	"kfynqDbDhg8Vw4GCRBZfcsSVQCwmRzQqqahGOf7AObwcMeWaal6Fq2m7Jos2SxsK26dfKfT/sspUWkmv",
	"LL97tacH0EI6pJYk6xUM23E/eG3z0W+QZ3fiNoutWFYTF/wv4GPI9lpnXRhuGWHxiqHrZZKw/DO2i2HL",
	"OVj37AIAOxkqRLIj9mwR0lLKc5kk57xRK6M/qeXynYI8fX9wfkZ33kr1Z/myj2uDfsvBT0AillOidH7s",
	"E5fuqLHi7WhenzcLltAf+ztd+1izDmhdnCU0Vc011kR+8T3nDbTL9odsYfoT89eSa9eIpCTd8wQKxjZI",
	"iim+A78oqGVn8E86vNAM/U66gFnlALN0m7a8SrVBOxc/McMeig8PbJa3rDJRTdC1qDM0r4/m9dmxK1pu",
	"rDCl5LLj48rklFZQpibzmjKpT6rkMrmiXtEnw0moVjP0tcmhqGyIQfjB+mqcmarlosBWX9FjYCVYKezS",
	"EwlYA/u8p5xY62rhbu7SZWHVlkBTsa8Qtg3wnzaUq1hJHUnsd7TtFaUd7pV9HG3mH2euiVZcfSO9ujY9",
	"Zk/Zw/4GqKrlp7JTV5RLY4WCMjF2eVyZujQ5oVzJTalqVi2MF7IFoUzuZmLl2FtKuoAdMV6rn0A9lJIW",
	"7s5c7NP0jGgFEZ/6TywH6ly/4g2Nb368eE95b27Kqs2QDz/euH6TfOo4Hxec8Y2137iLysfOrdzi7Y15",
	"leTs90qrS5dzzrW5Fe2m5n408UHtN5VsApcRSPMtWrxDG0jOPQQYuHfHKAYNiFPso3nsL6oRxyjKIxRp",
	"cMnwIFGzTFfV3BCVkO205RBTK101zLy1wemC17qmf4KSBvxeos+wgdABkZHOQ7qs2WWvPeVMZzJuukIy",
	"9gp/Gq/X+mIr1ujC2UWD1TEaou7ofYtNuQMMkobEdhLgBVg+qMJweVL9TngTMP81Yjtcnmw6mx4DMa0q",
	"MdWqAU6RzqbHOVsqIUj0N/jgWpG44uRCW7x3x7ZZnTeXeHX4JXKCnQEbBVrfSuyUJgMq4BnW7vM6gK9p",
	"uIbqkjtQ1veX9uFR0/2kgAyVYmmJfhNujbE6PYKVpU+wPfiJ7DtoZCFp1tKJdKNsrUcc1Ws54njktzVi",
	"b/ZczPZaB37HZ8BoyWsP+w3hmN//dGMK0UbCDdTkTQwV2mtMszpvnh/gB3QmHyUa9BAdvhOU1cl+g1U4",
	"1pNgyiZ75FeUA11xlAw+Qk9abO5I1/k1FEWfIXlpYEvmSX+j9oKjWVVyMS1BqYVdgBd8E6DLFLZv2ghk",
	"LUjy8ZauqGvs93Ea2EoAOoB2CS0c0ZBNVD1BCyjca27/W2+otR9mE8FACQv8BuaTXXBtP5l4qsBAx608",
	"9j1dwqegSqTZuws3oplmqXxvde3e3aT9uKoL+zmL/N97/gkEXMSy+lr5JxALe/QYzdB//8gTNGHgWjpZ",
	"0UpquUzMIlmpELdk6bIIeZDqjYQ8f4zLeMZZ33BJB+p7ORUgKyay8WxOyEdxBhWHFu7wfFrFR4Q8vbH6",
	"K0MHH4ujMLOqViLKrGW6tlUWUlaBMG32O1RpyEkg60vvLS5+qPQ1EUXnEUxLcVzLJinJtBQNJEhJlZrj",
	"KjZZU8uGzj04TqZuWxrPoaIZYoilJWrSI3GvAsUJW3mleeCHtlrkD+p3ggATdhAADn2Y5GdD0P6sTtu+",
	"ib0dA/b0uBmgRp+r7EkQ3ZJX+m5jo3rP9/8T2qQ/4Ma9GGBfQAw0uYlZnT1lj2kLLjboc085nHMm2BYt",
	"Kjo0gTy0oNbKrs9/iYkf1Wq1bHDbZh443MC9hw+dUgQzD2+JaAMcxFXgH277R5BLeBnOQRZN4tQqFdXe",
	"hB/8D+xTGgPWFRDJBlDWHlNOyvPYcwITvpSQ+Um5NBYnahGonoyuIS/Dep6bPFhfdZKJ7Ne0S18GyYHn",
	"uFv33r+bQnMiGdmmP+CXLXDfUPnK9sKVTSuSdSJj8EhNE50MH6ZjvPYmce+A4LdA7j5cy2WzZzJrtAew",
	"SjZHn009WF+ND6XE1VY/nvVCnoN9gFbyW/HOZ8EspBE+tNE466GN/iF+n0/zIqwernojzsJDnjtLkx5J",
	"t+7e+UC6R/LS+2RTuktc6QL43cWBvhx0HquW8ADUd9ybURIP1MQp6qnEZ1UAwt64vIXQ1aQnOEY7jcFk",
	"i98GP2uFRjY8Cl4EOb8Zc2jshGIrdVhdNuSc02lEw55zHUocDXj/A2TFui16ui12dGX4cackRnImHrvM",
	"byaOe83SN9+Yz/u95biv/6Fnh0R2EgDV4FQc3eXWSAwrFPq0MXAJtp+WRiJkdb+FGJgciMiwEzbgF0sL",
	"t8+J2DkROydiQ4lYLi3Rr5IjdVCdk5yrgsNsCbnqWZCJQ92FwS2eYUd6o3lnbkMrqWaRRFp2sz0IH47K",
	"G8r6+rpSsOyKUrPLxAT810e3l+DM8lZ0hiNC1rNyvJElGOA3ccrmGyctCSnyICv8XBH3HKn+9kg5x7dx",
	"bIx6a4RWiD4qAc1q3pmWBBj7Ez9L7pk2NA2JkmrOZ/gJsecDTkvgNDqKY7M2UV0SnF6IkWiRIXq3ZCJv",
	"jQiadz8T0v2Tk+xA4UL3pQfs3/DM4a4f79gveOlVQgOzZhzxx96o1N6REJHc34dk7KYl+u9ID1sSb51z",
	"T2j1DcKabNd7IcA/WBH3lK53IPSIvxBwiqDVpi3Y6+uXCuGmT1TNo4bVebFxXmycp/C3XGwE4OO/gTY8",
	"bqULfHAp8ak2XGbbiBj8aFdDYo9Qew0p92qzmjC2hLts4UZcjTev+llB5jP/OOIWd7kycUUnYv6X66j3",
	"Gg7b4fNZTxNodhCtDbdF4bV/nCY+8hbjDNdRFkgG1zaXwod3X4s5DLk/OJwZm8flshOjpICuBzEe7PPk",
	"MSE8fvLSf/XORx/udmjIAwwtTFrwiAnhI74beHgQIO6IH52Qfx7B9RdMiaFcMrxmR7de3koljEbegtve",
	"JO5fkc9m3ygre4VZyS/Dc2E/wDnbAzrW+MJ/E1NF6Ah4zJGrqquV/jpceamqq28bgX+coiipIApO9aNG",
	"d1idPfZfD/C4TnNgrhfURedZ40eOvX6zif5/DCnRZjjs6wtCATnK2ASrkgFdlKAOPeSUmnccQJsdoNd1",
	"L7m1+E2JVM47MHtCu+wxvpN+fe723OKc1C9RSuI66vADdbTL9v0Bf6gQPu1NU0E9EgLBiY9D8AXb8eqJ",
	"kA5jSLDAd/83QMZ+GTHxdcyuPVYV/U8TeoyrM6SOEcQJLErsNd/8vcPl05lM2dLUcsly3Okr2aks2lKB",
	"mw2NZNSqkVkbQ7N6jxS8CLrDfp+S2MNw2sNA6kt7Qw6Yh/4rHFHn8AzLQDiz3wte8YQo7a3EzzcIlho4",
	"nRKfJY+WduGzQt5ivJzbWt76/wAAAP//Rmk+BKhIAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
